### ISSUE TITLE
Helm commands fail with 403 error when using OCI registry

### ISSUE THREAD

**Issue by ayapejian-centeredge** [kube-logging/logging-operator#1522]
Trying to install the `v4.4.0` version of `logging-operator` helm chart.  Helm command comes straight from [documentation](https://kube-logging.dev/docs/install/) results in authorization error `403 Forbidden`.

Running on MacOS: `uname -a`: `Darwin myhost.lan 23.1.0 Darwin Kernel Version 23.1.0: Tue Sep 26 22:11:21 PDT 2023; root:xnu-10002.40.89.501.1~3/RELEASE_ARM64_T6000 arm64`

Short Output:

```shell
> helm upgrade --install --wait --create-namespace --namespace logging logging-operator oci://ghcr.io/kube-logging/helm-charts/logging-operator`

Release "logging-operator" does not exist. Installing it now.
Error: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Akube-logging%2Fhelm-charts%2Flogging-operator%3Apull&scope=repository%3Auser%2Fimage%3Apull&service=ghcr.io: 403 Forbidden
```

With Debug Logging:

```shell
> helm --debug upgrade --install --wait --create-namespace --namespace logging logging-operator oci://ghcr.io/kube-logging/helm-charts/logging-operator

history.go:56: [debug] getting history for release logging-operator
Release "logging-operator" does not exist. Installing it now.
install.go:214: [debug] Original chart version: ""
DEBU[0000] resolving                                     host=ghcr.io
DEBU[0000] do request                                    host=ghcr.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=Helm/3.13.0 request.method=HEAD url="https://ghcr.io/v2/kube-logging/helm-charts/logging-operator/manifests/4.4.0"
DEBU[0000] fetch response received                       host=ghcr.io response.header.content-length=73 response.header.content-type=application/json response.header.date="Tue, 10 Oct 2023 18:17:45 GMT" response.header.www-authenticate="Bearer realm=\"https://ghcr.io/token\",service=\"ghcr.io\",scope=\"repository:user/image:pull\"" response.header.x-github-request-id="CF6C:59A5:4BD6F0:6DDEA8:65259549" response.status="401 Unauthorized" url="https://ghcr.io/v2/kube-logging/helm-charts/logging-operator/manifests/4.4.0"
DEBU[0000] Unauthorized                                  header="Bearer realm=\"https://ghcr.io/token\",service=\"ghcr.io\",scope=\"repository:user/image:pull\"" host=ghcr.io
DEBU[0001] do request                                    host=ghcr.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=Helm/3.13.0 request.method=HEAD url="https://ghcr.io/v2/kube-logging/helm-charts/logging-operator/manifests/4.4.0"
INFO[0001] trying next host                              error="failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Akube-logging%2Fhelm-charts%2Flogging-operator%3Apull&scope=repository%3Auser%2Fimage%3Apull&service=ghcr.io: 403 Forbidden" host=ghcr.io
Error: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Akube-logging%2Fhelm-charts%2Flogging-operator%3Apull&scope=repository%3Auser%2Fimage%3Apull&service=ghcr.io: 403 Forbidden
helm.go:84: [debug] failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Akube-logging%2Fhelm-charts%2Flogging-operator%3Apull&scope=repository%3Auser%2Fimage%3Apull&service=ghcr.io: 403 Forbidden
```

**Comment by pepov** [comment]
The documentation misses to mention that although the package is available publicly, you still need to have a classic API token on github and you have to authenticate to ghcr.io using your username and the token as the password:
```
helm registry login https://ghcr.io
```

**Comment by willzhang** [comment]
Is there a way to avoid logging in? This is too troublesome and cannot be automatically pulled from the Github action on the public network

**Comment by ayapejian-centeredge** [comment]
> Is there a way to avoid logging in? This is too troublesome and cannot be automatically pulled from the Github action on the public network

I was thinking the same thing, prior we have a devcontainer that pulls all that's needed and was fully automated.  Would be nice if there was a way to fetch the artifacts without having to complete this step.  Maybe a mirror of the repo?  Let me know if you find something out.

**Comment by pepov** [comment]
The latest helm release with the fix is out, please verify that you issue has been resolved: https://github.com/helm/helm/releases/tag/v3.13.1

**Comment by ayapejian-centeredge** [comment]
> The latest helm release with the fix is out, please verify that you issue has been resolved: https://github.com/helm/helm/releases/tag/v3.13.1

Thank you much, just tested with `helm upgrade --install --wait --create-namespace --namespace logging logging-operator oci://ghcr.io/kube-logging/helm-charts/logging-operator` in a kind cluster and all worked perfectly.  👍

**Comment by pepov** [comment]
this is going to be noted in the docs: https://github.com/kube-logging/kube-logging.github.io/pull/194

**Comment by pepov** [comment]
Even after an upgrade to the latest helm version, an invalid token stuck in the credential store can cause issues, see:
According to https://github.com/kube-logging/kube-logging.github.io/pull/194#issuecomment-1765290381

**Comment by BSVogler** [comment]
I found this thread via google as I was searching for a related issue. Thank you @pepov.
So for other people having this issue: Even in helm v3.18.3 this is still an issue. Is there some bug ticket in the helm repo?

**Comment by OscarPoels** [comment]
@BSVogler 
I don't think it is an issue anymore, I am also using the Helm v3.18.3 and it's working fine,
If you are using a Chart.yaml file and using it as a dependency, you need to use oci://ghcr.io/kube-logging/helm-charts as the repository and not the full path, this is mentioned in the [documentation](https://kube-logging.dev/docs/install/) as it is the same "problem" as Terraform
```
If you’re installing the Helm chart from Terraform, reference the repository as repository = "oci://ghcr.io/kube-logging/helm-charts/" (without the logging-operator suffix). Otherwise, you’ll get a [403 Forbidden error](https://github.com/hashicorp/terraform-provider-helm/issues/1291).
```

**Comment by BSVogler** [comment]
@OscarPoels You might be experiencing a different situation since I had an invalid login token and this was causing issues with the public repo. But thanks for your hint.
